### ISSUE TITLE
Fix for working on native Windows

### ISSUE THREAD

**Issue by mrwidde** [junglejs/junglejs#3]
Hi,

Thanks for your work and the interesting project. I went through the quickstart and started the templateapp. When i browse the app and check my developer console i get "Uncaught ReferenceError: SFile is not defined". Everything seems to work - but it's annoying with the error message in the console.

Also when running the local server, i get a 404 for service-worker.js. Is it possible to do anything about these two things?

Thank you again.

**Comment by ConProgramming** [comment]
Hmm good to know. This might be an issue for [junglejs/template](https://github.com/junglejs/template) but I'll take a look and see where the problem is arising from. Thanks!

**Comment by mrwidde** [comment]
Thanks for looking into it, it might be isolated to the template.

However i noticed that clicking the button that should trigger the alert() also isn't working. Maybe related to the SFile is not defined and it's breaking all the js.

**Comment by ConProgramming** [comment]
Hmm... you sure you're on the latest version of the template? I had a version of it up for about 6 hours (when I first switched to SSR) where the alert() wasn't working and I think all the JS was broken. The latest [quick start](https://www.junglejs.org/docs/quick-start/) the alert works fine for me.

**Comment by mrwidde** [comment]
![Capture](https://user-images.githubusercontent.com/3201099/87227447-4dc00b00-c39b-11ea-98f3-665d18290967.PNG)
This is how it looks for me when running the template from the quickstart. I have tested it on two different computers and with the same result. "Sfile is not defined" and the alert is not working on /blog/about-blog/

**Comment by ConProgramming** [comment]
Are you on Windows? It works with WSL on Windows but I haven't been able to try it on native Windows... if so then I'll go through the code and make sure I'm using the right `path.join` and all that

**Comment by mrwidde** [comment]
Yes, both computers i have tested with run on Windows 10

Ok, so this might be the problem then.

**Comment by ConProgramming** [comment]
Yep this is definitely it sorry, I'm used to using Mac/Linux and when I switched to Windows only used WSL... I'll start working on this asap (or you can drop a PR if ya want it done quicker).

**Comment by mrwidde** [comment]
Cool that we figured that out!

I can try do a PR if i find some time for it during this weekend. You think the issue has something to do with paths on native windows then?

**Comment by ConProgramming** [comment]
Yep, I tried to do path.join in a lot of places but didn't check over it everywhere specifically, so I'm sure I forgot it somewhere.

Also looks weird with that random `outelog` being inserted before the files? It looks like Sapper a similar error a couple years ago? https://github.com/sveltejs/sapper-template/issues/77

**Comment by mrwidde** [comment]
PR for this issue is created.
